apiVersion: v1
kind: Pod
metadata:
  name: tito-sql 
  labels:
    version: "1.5"
    app: tito
    name: tito-sql
    tier: backend
spec:
  containers:
    - name: tito-sql
      image: vmeoc/tito-sql:V1.5
      ports:
      - containerPort: 3306
      env:
      - name: MYSQL_ROOT_PASSWORD
        value: Tito2016
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
